/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import ManejoDatos.ConexionBD;

/**
 *
 * @author Edwin
 */
public class VistaGestionGrupos extends javax.swing.JFrame {

    /**
     * Creates new form VistaGestionGrupos
     */
    public VistaGestionGrupos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAdminAlumno = new javax.swing.JButton();
        btnAdminProfesor = new javax.swing.JButton();
        btnAdminAsignatura = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnAdminGrupos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de Grupos Escolares");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Sistema de Gestion de Grupos Escolares");

        btnAdminAlumno.setText("Administrar Alumno");
        btnAdminAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminAlumnoActionPerformed(evt);
            }
        });

        btnAdminProfesor.setText("Administrar Profesor");
        btnAdminProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminProfesorActionPerformed(evt);
            }
        });

        btnAdminAsignatura.setText("Administrar Asignatura");
        btnAdminAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminAsignaturaActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnAdminGrupos.setText("Administrar Grupos");
        btnAdminGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminGruposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdminAsignatura)
                            .addComponent(btnAdminProfesor)
                            .addComponent(btnAdminAlumno)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAdminGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(btnAdminAlumno)
                .addGap(18, 18, 18)
                .addComponent(btnAdminProfesor)
                .addGap(17, 17, 17)
                .addComponent(btnAdminAsignatura)
                .addGap(18, 18, 18)
                .addComponent(btnAdminGrupos)
                .addGap(47, 47, 47)
                .addComponent(btnSalir)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminAsignaturaActionPerformed

        VistaAdministradorAsignatura ventanaAdminAsignatura = new VistaAdministradorAsignatura(this);
        ventanaAdminAsignatura.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAdminAsignaturaActionPerformed

    private void btnAdminAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminAlumnoActionPerformed
        VistaAdministradorAlumno ventanaAdminAlumno = new VistaAdministradorAlumno(this);
        ventanaAdminAlumno.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAdminAlumnoActionPerformed

    private void btnAdminProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminProfesorActionPerformed
        
        VistaAdministradorProfesor ventanaAdminProfesor = new VistaAdministradorProfesor(this);
        ventanaAdminProfesor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAdminProfesorActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAdminGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminGruposActionPerformed
        // TODO add your handling code here:
        VistaAdministradorGrupo ventanaAdminGrupo = new VistaAdministradorGrupo(this);
        ventanaAdminGrupo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAdminGruposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaGestionGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaGestionGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaGestionGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaGestionGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaGestionGrupos().setVisible(true);
                if(ConexionBD.Conectar() != 0){
                    ConexionBD.GenerarBD();
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminAlumno;
    private javax.swing.JButton btnAdminAsignatura;
    private javax.swing.JButton btnAdminGrupos;
    private javax.swing.JButton btnAdminProfesor;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
