/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.AdministradorDeAsignatura;
import ManejoDatos.ConexionBD;
import Modulo.Asignatura;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristian Xool
 */
public class VistaRegistrarAsignatura extends javax.swing.JFrame {

    /**
     * Creates new form VistaRegistrarAsignatura
     */
    public VistaRegistrarAsignatura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombreAsignatura = new javax.swing.JTextField();
        etiquetaNombre = new javax.swing.JLabel();
        etiquetaClave = new javax.swing.JLabel();
        txtClaveAsignatura = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        etiquetaTitulo = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        txtNombreAsignatura.setDocument(new ManejoDatos.ValidadorDeLongitudTexto(60));
        txtNombreAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreAsignaturaActionPerformed(evt);
            }
        });
        txtNombreAsignatura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreAsignaturaKeyTyped(evt);
            }
        });

        etiquetaNombre.setText("Nombre:");

        etiquetaClave.setText("Clave");

        txtClaveAsignatura.setDocument(new ManejoDatos.ValidadorDeLongitudTexto(8));
        txtClaveAsignatura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClaveAsignaturaKeyTyped(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        etiquetaTitulo.setText("Registrar Asignatura");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaTitulo)
                .addGap(151, 151, 151))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaNombre)
                    .addComponent(etiquetaClave))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(btnCancelar))
                    .addComponent(txtNombreAsignatura)
                    .addComponent(txtClaveAsignatura))
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(etiquetaTitulo)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaNombre))
                        .addGap(53, 53, 53)
                        .addComponent(txtClaveAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(etiquetaClave))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAsignaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAsignaturaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        String nombre = txtNombreAsignatura.getText();
        String clave = txtClaveAsignatura.getText();
        
        Asignatura unaAsignatura = new Asignatura(clave, nombre);
        
        if(txtNombreAsignatura.getText().equals("")){
            JOptionPane.showMessageDialog(null, "ERROR: Llenar todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            
            String msjResultado = AdministradorDeAsignatura.Registrar(unaAsignatura);
            JOptionPane.showMessageDialog(null, msjResultado);
            if(JOptionPane.showConfirmDialog(null, "Desea registrar otra?",
                    "Registrar", JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION){
                this.dispose();
                
            }
        }
        
        txtNombreAsignatura.setText("");
        txtClaveAsignatura.setText("");

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtNombreAsignaturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreAsignaturaKeyTyped
        // TODO add your handling code here:
        char validacion = evt.getKeyChar();
        
        if((validacion<'a' || validacion>'z')&&(validacion<'A' || validacion>'Z')&&
                (validacion<' ' || validacion>' ')&&(validacion<'0' || validacion>'9'))
            evt.consume();
    }//GEN-LAST:event_txtNombreAsignaturaKeyTyped

    private void txtClaveAsignaturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveAsignaturaKeyTyped
        // TODO add your handling code here:
        char validacion = evt.getKeyChar();
        
        if((validacion<'A' || validacion>'Z')&&(validacion<'0' || validacion>'9')&&
                (validacion<'-' || validacion>'-'))evt.consume();
    }//GEN-LAST:event_txtClaveAsignaturaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrarAsignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrarAsignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrarAsignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrarAsignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }
    
    /*protected MaskFormatter crearFormato(String s) {
        MaskFormatter formato = null;
        try {
            formato = new MaskFormatter(s);
        } catch (java.text.ParseException exc) {
            System.err.println("El MaskFormatter es incorrecto: " + exc.getMessage());
            System.exit(-1);
        }
        return formato;
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel etiquetaClave;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JTextField txtClaveAsignatura;
    private javax.swing.JTextField txtNombreAsignatura;
    // End of variables declaration//GEN-END:variables
}
