/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.AdministradorDeProfesor;
import ManejoDatos.ConexionBD;
import ManejoDatos.ValidadorDeLongitudTexto;
import Modulo.Profesor;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristian Xool
 */
public class VistaModificarProfesor extends javax.swing.JFrame {

    /**
     * Creates new form VistaModificarProfesor
     */
    public VistaModificarProfesor() {
        initComponents();
    }
    
    public VistaModificarProfesor(Profesor profesorAModificar){
        initComponents();
        txtNombreProfesor.setText(profesorAModificar.GetNombre());
        txtApellidosProfesor.setText(profesorAModificar.GetApellidos());
        txtClaveProfesor.setText(profesorAModificar.GetClave());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        etiquetaTitulo = new javax.swing.JLabel();
        txtClaveProfesor = new javax.swing.JTextField();
        etiquetaClave = new javax.swing.JLabel();
        txtApellidosProfesor = new javax.swing.JTextField();
        etiquetaApellidos = new javax.swing.JLabel();
        txtNombreProfesor = new javax.swing.JTextField();
        etiquetaNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        etiquetaTitulo.setText("Modificar Profesor");

        txtClaveProfesor.setDocument(new ManejoDatos.ValidadorDeLongitudTexto(8));
        txtClaveProfesor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClaveProfesorKeyTyped(evt);
            }
        });

        etiquetaClave.setText("Clave:");

        txtApellidosProfesor.setDocument(new ManejoDatos.ValidadorDeLongitudTexto(30));
        txtApellidosProfesor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosProfesorKeyTyped(evt);
            }
        });

        etiquetaApellidos.setText("Apellidos:");

        txtNombreProfesor.setDocument(new ManejoDatos.ValidadorDeLongitudTexto(30));
        txtNombreProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProfesorActionPerformed(evt);
            }
        });
        txtNombreProfesor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreProfesorKeyTyped(evt);
            }
        });

        etiquetaNombre.setText("Nombre:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaTitulo)
                .addGap(151, 151, 151))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaNombre)
                    .addComponent(etiquetaApellidos)
                    .addComponent(etiquetaClave))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(btnCancelar))
                    .addComponent(txtNombreProfesor)
                    .addComponent(txtApellidosProfesor)
                    .addComponent(txtClaveProfesor))
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(etiquetaTitulo)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaNombre))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaApellidos)
                    .addComponent(txtApellidosProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaClave)
                    .addComponent(txtClaveProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        String nombre = txtNombreProfesor.getText();
        String apellidos = txtApellidosProfesor.getText();
        String clave = txtClaveProfesor.getText();

        Profesor unProfesor = new Profesor(clave, nombre, apellidos);
        
        if(txtNombreProfesor.getText().equals("") || txtApellidosProfesor.getText().equals("")){
            JOptionPane.showMessageDialog(null, "ERROR: Llenar todos los  campos",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            if(clave.length() < ValidadorDeLongitudTexto.LONGITUD_CLAVE){
                JOptionPane.showMessageDialog(null, "ERROR: Matricula debe ser de 8 numeros. Ej: 12345678",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
            else {
                String msjResultado = AdministradorDeProfesor.Modificar(unProfesor);
                JOptionPane.showMessageDialog(null, msjResultado, "Resultado",
                        JOptionPane.INFORMATION_MESSAGE);
                if(JOptionPane.showConfirmDialog(null, "Desea modificar otro?",
                        "Modificar", JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION){
                    this.dispose();
                }
            }
        }
        
        txtNombreProfesor.setText("");
        txtApellidosProfesor.setText("");
        txtClaveProfesor.setText("");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNombreProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProfesorActionPerformed

    private void txtNombreProfesorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreProfesorKeyTyped
        // TODO add your handling code here:
        char validacion = evt.getKeyChar();
        
        if((validacion < 'a' || validacion > 'z')&&(validacion < 'A' || validacion > 'Z')&&(validacion < ' ' || validacion > ' '))evt.consume();
    }//GEN-LAST:event_txtNombreProfesorKeyTyped

    private void txtApellidosProfesorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosProfesorKeyTyped
        // TODO add your handling code here:
        char validacion = evt.getKeyChar();
        
        if((validacion < 'a' || validacion > 'z')&&(validacion < 'A' || validacion > 'Z')&&(validacion < ' ' || validacion > ' '))evt.consume();
    }//GEN-LAST:event_txtApellidosProfesorKeyTyped

    private void txtClaveProfesorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveProfesorKeyTyped
        // TODO add your handling code here:
        char validacion = evt.getKeyChar();
        
        if(validacion < '0' || validacion > '9')evt.consume();
    }//GEN-LAST:event_txtClaveProfesorKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaModificarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaModificarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaModificarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaModificarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if(ConexionBD.Conectar() == -1){
                    ConexionBD.GenerarBD();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel etiquetaApellidos;
    private javax.swing.JLabel etiquetaClave;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JTextField txtApellidosProfesor;
    private javax.swing.JTextField txtClaveProfesor;
    private javax.swing.JTextField txtNombreProfesor;
    // End of variables declaration//GEN-END:variables
}
