/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.AdministradorDeAsignatura;
import Controlador.AdministradorDeGrupo;
import Controlador.AdministradorDeProfesor;
import ManejoDatos.ValidadorDeEstado;
import ManejoDatos.ValidadorDeFormato;
import ManejoDatos.ValidadorDeLongitudTexto;
import Modulo.Asignatura;
import Modulo.GrupoEscolar;
import Modulo.Profesor;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Aaron
 */
public class VistaRegistrarGrupoEscolar extends javax.swing.JFrame {

    /**
     * Creates new form VistaRegistrarGrupoEscolar
     */
    public VistaRegistrarGrupoEscolar() {
        initComponents();
        cargarCombosBox();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtClaveGrupo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAulaGrupo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboAsignaturas = new javax.swing.JComboBox();
        comboProfesores = new javax.swing.JComboBox();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtHorarioGrupo = new javax.swing.JFormattedTextField(
            ValidadorDeFormato.crearFormato("##:##-##:##"));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Clave");

        jLabel2.setText("Asignatura");

        jLabel3.setText("Profesor");

        txtClaveGrupo.setDocument(new ManejoDatos.ValidadorDeLongitudTexto(8));
        txtClaveGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveGrupoActionPerformed(evt);
            }
        });
        txtClaveGrupo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClaveGrupoKeyTyped(evt);
            }
        });

        jLabel4.setText("Aula");

        txtAulaGrupo.setDocument(new ManejoDatos.ValidadorDeLongitudTexto(1));
        txtAulaGrupo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAulaGrupoKeyTyped(evt);
            }
        });

        jLabel5.setText("Horario");

        jLabel6.setText("Registrar Grupo");

        comboAsignaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAsignaturasActionPerformed(evt);
            }
        });

        comboProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProfesoresActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(txtClaveGrupo)
                            .addComponent(txtAulaGrupo)
                            .addComponent(comboAsignaturas, 0, 166, Short.MAX_VALUE)
                            .addComponent(comboProfesores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtHorarioGrupo))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtClaveGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(comboAsignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(comboProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtHorarioGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtAulaGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClaveGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveGrupoActionPerformed

    private void comboAsignaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAsignaturasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAsignaturasActionPerformed

    private void comboProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProfesoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboProfesoresActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
        if(txtAulaGrupo.getText().equals("") || txtHorarioGrupo.getText().replaceAll("\\s","").equals(":-:") ||
                comboAsignaturas.getSelectedIndex() == ValidadorDeEstado.NO_SELECCION ||
                comboProfesores.getSelectedIndex() == ValidadorDeEstado.NO_SELECCION){
            JOptionPane.showMessageDialog(null, "ERROR: Llenar todos los campos", 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            if(txtClaveGrupo.getText().length() < ValidadorDeLongitudTexto.LONGITUD_CLAVE){
                JOptionPane.showMessageDialog(null, "ERROR: Clave debe ser de 8 numeros. Ej: 12345678", 
                        "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                String claveGrupo = txtClaveGrupo.getText();
                Asignatura unaAsignatura = ((Asignatura)comboAsignaturas.getSelectedItem());
                Profesor unProfesor =((Profesor)comboProfesores.getSelectedItem());
                String aula = txtAulaGrupo.getText();
                String horario = txtHorarioGrupo.getText();
                
                GrupoEscolar unGrupo = new GrupoEscolar(claveGrupo, unaAsignatura, unProfesor, aula, horario);
                String msjResultado = AdministradorDeGrupo.Registrar(unGrupo);
                JOptionPane.showMessageDialog(null, msjResultado);
                if(JOptionPane.showConfirmDialog(null, "Desea registrar otro?",
                        "Registrar", JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION){
                    this.dispose();
                }else{
                    txtClaveGrupo.setText("");
                    comboAsignaturas.setSelectedIndex(ValidadorDeEstado.NO_SELECCION);
                    comboProfesores.setSelectedIndex(ValidadorDeEstado.NO_SELECCION);
                    txtAulaGrupo.setText("");
                    txtHorarioGrupo.setText("");
                }
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtClaveGrupoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveGrupoKeyTyped
        // TODO add your handling code here:
        char validacion = evt.getKeyChar();
        
        if(validacion < '0' || validacion > '9')evt.consume();
    }//GEN-LAST:event_txtClaveGrupoKeyTyped

    private void txtAulaGrupoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAulaGrupoKeyTyped
        // TODO add your handling code here:
        char validacion = evt.getKeyChar();
        
        if(validacion < 'A' || validacion > 'Z')evt.consume();
    }//GEN-LAST:event_txtAulaGrupoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrarGrupoEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrarGrupoEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrarGrupoEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrarGrupoEscolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    
    private void cargarCombosBox(){
        ArrayList<Asignatura> listaAsignaturas;
        ArrayList<Profesor> listaProfesores;
        
        listaAsignaturas = AdministradorDeAsignatura.ObtenerLista();
        listaProfesores = AdministradorDeProfesor.ObtenerLista();
        for(int i=0; i<listaAsignaturas.size(); i++){
            
            comboAsignaturas.addItem(((Asignatura)listaAsignaturas.get(i)));
            
        }
        for(int i=0; i<listaProfesores.size(); i++){
            
            comboProfesores.addItem(((Profesor)listaProfesores.get(i)));
        }
        
    }
 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox comboAsignaturas;
    private javax.swing.JComboBox comboProfesores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtAulaGrupo;
    private javax.swing.JTextField txtClaveGrupo;
    private javax.swing.JFormattedTextField txtHorarioGrupo;
    // End of variables declaration//GEN-END:variables
}
